### ISSUE TITLE
How to add custom attributes?

### ISSUE THREAD

**Issue by BrayanCaro** [nedwors/navigator#6]
I wasn't able to add custom attributes per Item, I'm wondering if we can add a method like:

```php
Nav::item('Dashboard')->attributes([
    'foo' => 'bar',
])

$item->attributes // ['foo' => 'bar']
``` 

Btw, this project is awesome!

**Comment by nedwors** [comment]
Hey @BrayanCaro!

The `Item` class extends Laravel's `Fluent` class, so custom properties can be added on the fly - see the docs here: 

**https://github.com/nedwors/navigator#api**
> It's worth noting at this point that Item extends Illuminate\Support\Fluent to allow for custom methods/properties on a per project basis. Also, Nav is macroable to allow for custom functionality in your projects.

`Fluent` stores custom attributes in an existing `$attributes` property which is why you may not be seeing it work with `->attributes`. Try something like:

```php
Nav::item('Dashboard')->meta([
    'foo' => 'bar',
])

$item->meta // ['foo' => 'bar']
```
And you should see it working - I have in Tinkerwell 👍 

Thanks!

**Comment by BrayanCaro** [comment]
I realize I didn’t understand the usage of the Fluent class

Thanks a lot ☺️
